class SubscriberDetail {
  int id;
  String accountPin;
  String accountType;
  String activatedAt;
  int affiliateId;
  String autopayEnrolledAt;
  int companyId;
  String contactNumber;
  String createdAt;
  String creditScoreUpdatedAt;
  Null creditScore;
  Null dateOfBirth;
  Null deactivatedAt;
  String email;
  String firstName;
  String lastName;
  String magneticUserCreatedAt;
  String name;
  String organizationName;
  int referrerSubscriberId;
  bool sendEmails;
  bool sendTexts;
  Null ssnLastFour;
  String state;
  int taxExemptionCodeId;
  String timeZone;
  String updatedAt;
  String uuid;
  bool autopayEnrolled;
  int companyProfileId;
  String currentBalance;
  int currentBillingStatementId;
  String currentDueAt;
  String depositBalance;
  String pastDueAt;
  String pastDueBalance;
  int primaryLineId;
  String totalBalance;
  String totalCreditBalance;

  SubscriberDetail.fromJson(Map<String, dynamic> json) {
    List lstSubscriber = json["subscribers"] ?? new List();
    Map mapSubscriber = lstSubscriber[0] ?? new Map();

    id = mapSubscriber['id'];
    accountPin = mapSubscriber['account_pin'];
    accountType = mapSubscriber['account_type'];
    activatedAt = mapSubscriber['activated_at'];
    affiliateId = mapSubscriber['affiliate_id'];
    autopayEnrolledAt = mapSubscriber['autopay_enrolled_at'];
    companyId = mapSubscriber['company_id'];
    contactNumber = mapSubscriber['contact_number'];
    createdAt = mapSubscriber['created_at'];
    creditScoreUpdatedAt = mapSubscriber['credit_score_updated_at'];
    creditScore = mapSubscriber['credit_score'];
    dateOfBirth = mapSubscriber['date_of_birth'];
    deactivatedAt = mapSubscriber['deactivated_at'];
    email = mapSubscriber['email'];
    firstName = mapSubscriber['first_name'];
    lastName = mapSubscriber['last_name'];
    magneticUserCreatedAt = mapSubscriber['magnetic_user_created_at'];
    name = mapSubscriber['name'];
    organizationName = mapSubscriber['organization_name'];
    referrerSubscriberId = mapSubscriber['referrer_subscriber_id'];
    sendEmails = mapSubscriber['send_emails'];
    sendTexts = mapSubscriber['send_texts'];
    ssnLastFour = mapSubscriber['ssn_last_four'];
    state = mapSubscriber['state'];
    taxExemptionCodeId = mapSubscriber['tax_exemption_code_id'];
    timeZone = mapSubscriber['time_zone'];
    updatedAt = mapSubscriber['updated_at'];
    uuid = mapSubscriber['uuid'];
    autopayEnrolled = mapSubscriber['autopay_enrolled'];
    companyProfileId = mapSubscriber['company_profile_id'];
    currentBalance = mapSubscriber['current_balance'];
    currentBillingStatementId = mapSubscriber['current_billing_statement_id'];
    currentDueAt = mapSubscriber['current_due_at'];
    depositBalance = mapSubscriber['deposit_balance'];
    pastDueAt = mapSubscriber['past_due_at'];
    pastDueBalance = mapSubscriber['past_due_balance'];
    primaryLineId = mapSubscriber['primary_line_id'];
    totalBalance = mapSubscriber['total_balance'];
    totalCreditBalance = mapSubscriber['total_credit_balance'];
  }
}
